SELECT CURTIME();
SELECT CURDATE();

SELECT DATE_FORMAT(NOW(), '%w');
SELECT DAYOFWEEK(NOW());

SELECT DATE_FORMAT(NOW(), '%W');
SELECT DAYNAME(NOW());

SELECT DATE_FORMAT(CURDATE(), '%m/%d/%y');

SELECT DATE_FORMAT(NOW(), '%M %D at %l:%i');

CREATE TABLE tweets (
    content VARCHAR(140),
    username VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW()
)
